# Generated by Django 5.2.12 on 2026-03-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='citizenship',
            field=models.CharField(blank=True, max_length=100, verbose_name='Citizenship'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_scholar',
            field=models.URLField(blank=True, verbose_name='Google Scholar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='institution',
            field=models.CharField(blank=True, max_length=255, verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='institution_address',
            field=models.TextField(blank=True, verbose_name='Institution address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='orcid',
            field=models.CharField(blank=True, max_length=50, verbose_name='ORCID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Title'),
        ),
    ]
