# Generated by Django 5.2.12 on 2026-03-22 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='article_versions/', verbose_name='Version file')),
                ('version_number', models.PositiveIntegerField(verbose_name='Version number')),
                ('comment', models.TextField(blank=True, verbose_name='Author comment')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='articles.article', verbose_name='Article')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_article_versions', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('article', 'version_number')},
            },
        ),
    ]
