# Generated by Django 5.2.12 on 2026-03-27 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articleversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='coauthors',
            field=models.ManyToManyField(blank=True, related_name='coauthored_articles', to=settings.AUTH_USER_MODEL, verbose_name='Co-authors'),
        ),
        migrations.CreateModel(
            name='ArticleCoauthorInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used at')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coauthor_invites', to='articles.article', verbose_name='Article')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_coauthor_invites', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_coauthor_invites', to=settings.AUTH_USER_MODEL, verbose_name='Used by')),
            ],
        ),
    ]
