# Generated by Django 5.2.12 on 2026-03-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_coauthors_articlecoauthorinvite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecoauthorinvite',
            name='used_at',
        ),
        migrations.RemoveField(
            model_name='articlecoauthorinvite',
            name='used_by',
        ),
    ]
