# Generated by Django 5.2.12 on 2026-03-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_articlecoauthorinvite_used_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='coauthors',
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('abstract_submitted', 'Abstract submitted'), ('abstract_accepted', 'Abstract accepted'), ('abstract_rejected', 'Abstract rejected'), ('submitted', 'Full article submitted'), ('under_review', 'Under review'), ('revision_required', 'Revision required'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=30, verbose_name='Status'),
        ),
    ]
