# Generated by Django 5.2.12 on 2026-03-27 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_article_coauthors_alter_article_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='coauthors',
            field=models.ManyToManyField(blank=True, related_name='coauthored_articles', to=settings.AUTH_USER_MODEL, verbose_name='Co-authors'),
        ),
    ]
