# Generated by Django 5.2.12 on 2026-03-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_coauthors'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract_admin_comment',
            field=models.TextField(blank=True, default='', verbose_name='Abstract admin comment'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('abstract_submitted', 'Abstract submitted'), ('abstract_revision_requested', 'Abstract revision requested'), ('abstract_resubmitted', 'Abstract resubmitted'), ('abstract_approved', 'Abstract approved'), ('abstract_rejected', 'Abstract rejected'), ('submitted', 'Full article submitted'), ('under_review', 'Under review'), ('revision_required', 'Revision required'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=30, verbose_name='Status'),
        ),
    ]
