# Generated by Django 5.2.12 on 2026-03-23 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='allowed_authors',
            field=models.ManyToManyField(blank=True, related_name='allowed_books', to=settings.AUTH_USER_MODEL, verbose_name='Allowed authors'),
        ),
        migrations.AddField(
            model_name='book',
            name='submission_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submission deadline'),
        ),
        migrations.AddField(
            model_name='book',
            name='submission_mode',
            field=models.CharField(choices=[('all', 'All authors can submit'), ('invitation', 'Only invited authors can submit')], default='all', max_length=20, verbose_name='Submission mode'),
        ),
    ]
