# Generated by Django 5.2.12 on 2026-03-27 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_allowed_authors_book_submission_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='submission_mode',
            field=models.CharField(choices=[('invitation', 'Only invited authors can submit')], default='invitation', max_length=20, verbose_name='Submission mode'),
        ),
        migrations.CreateModel(
            name='BookAuthorInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_invites', to='books.book', verbose_name='Book')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_book_author_invites', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
        ),
    ]
