# Generated by Django 5.2.12 on 2026-03-22 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_article_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('review_submitted', 'Review submitted')], default='assigned', max_length=30, verbose_name='Assignment status')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned at')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='articles.article', verbose_name='Article')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
            ],
            options={
                'verbose_name': 'Review assignment',
                'verbose_name_plural': 'Review assignments',
                'unique_together': {('article', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('recommendation', models.CharField(choices=[('accept', 'Accept'), ('revision', 'Revision required'), ('reject', 'Reject')], max_length=20, verbose_name='Recommendation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reviews.reviewassignment', verbose_name='Assignment')),
            ],
        ),
    ]
