# Generated by Django 5.2.12 on 2026-03-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reviews/', verbose_name='Review file'),
        ),
    ]
