# Generated by Django 5.2.12 on 2026-03-22 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.reviewassignment', verbose_name='Assignment'),
        ),
    ]
