# Generated by Django 5.2.12 on 2026-03-23 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articleversion'),
        ('reviews', '0003_alter_review_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='article_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='articles.articleversion', verbose_name='Article version'),
        ),
    ]
