# Generated by Django 5.2.12 on 2026-03-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articleversion'),
        ('reviews', '0004_review_article_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('assignment', 'article_version'), name='unique_review_per_assignment_and_version'),
        ),
    ]
