# Generated by Django 5.2.12 on 2026-03-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
